/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/low_poly_80s_computer_v3.glb --transform 
Files: public/low_poly_80s_computer_v3.glb [614.34KB] > C:\Users\jawha\OneDrive\Documents\code\portfo\low_poly_80s_computer_v3-transformed.glb [93.28KB] (85%)
Author: SketchyBot (https://sketchfab.com/SketchyB0t_3D_Fabrication)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-80s-computer-v3-daf8d397f771445496844216d900c0f8
Title: Low Poly 80's Computer V3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/low_poly_80s_computer_v3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['ComputerTower-LowPoly003_Old_Computer_V3_0'].geometry} material={materials.Old_Computer_V3} rotation={[-3.136, Math.PI / 2, 0]} scale={0.234} />
      <mesh geometry={nodes['ComputerTower-LowPoly003_Screen001_0'].geometry} material={materials['Screen.001']} rotation={[-3.136, Math.PI / 2, 0]} scale={0.234} />
    </group>
  )
}

useGLTF.preload('/low_poly_80s_computer_v3-transformed.glb')
