/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/adam_stylised.glb --transform 
Files: public/adam_stylised.glb [9.51MB] > /home/nt-javkhlan_ts/Documents/code/portfo/adam_stylised-transformed.glb [644.93KB] (93%)
Author: Wenedi (^-^)/ (https://sketchfab.com/Wenedi)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/adam-stylised-fan-art-59a1d9bf7d1d4b7eabab7b44f8c5b297
Title: Adam - Stylised Fan Art
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AdamStylised(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL+'/adam_stylised-transformed.glb')
  materials.M_Adam_TorsoHead.wireframe = true
  materials.M_Adam_TorsoHead_NoCloth.wireframe = true
  materials.M_Adam_ArmsLegs.wireframe = true
  materials.M_Adam_Screen.wireframe = true
  materials.M_Adam_ArmsLegs_NoCloth.wireframe = true
  
  materials.M_Adam_TorsoHead.color.set('#c9e3f3')
  materials.M_Adam_TorsoHead_NoCloth.color.set('#c9e3f3')
  materials.M_Adam_ArmsLegs.color.set('#c9e3f3')
  materials.M_Adam_Screen.color.set('#c9e3f3')
  materials.M_Adam_ArmsLegs_NoCloth.color.set('#c9e3f3')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Adam_posed_M_Adam_TorsoHead_0.geometry} material={materials.M_Adam_TorsoHead} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Adam_posed_NoCloth_M_Adam_TorsoHead_NoCloth_0.geometry} material={materials.M_Adam_TorsoHead_NoCloth} position={[0.389, 0, -0.383]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Adam_posed_M_Adam_ArmsLegs_0.geometry} material={materials.M_Adam_ArmsLegs} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Adam_posed_M_Adam_Screen_0.geometry} material={materials.M_Adam_Screen} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Adam_posed_NoCloth_M_Adam_ArmsLegs_NoCloth_0.geometry} material={materials.M_Adam_ArmsLegs_NoCloth} position={[0.389, 0, -0.383]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/adam_stylised-transformed.glb')
