/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cyber_pulse.glb 
Author: lain (https://sketchfab.com/lain_dev)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cyber-pulse-wavy-ring-animated-f6e2df1c51fc4e6eb9a0ce3087e116e7
Title: Cyber Pulse Wavy Ring (Animated)
*/

import { useEffect,useRef,useMemo }from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

export function CyberPulse({ customColor, ...props }) {
  const group = useRef()
  const { nodes,scene, materials, animations } = useGLTF(process.env.PUBLIC_URL+'/cyber_pulse.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    if (names.length > 0) {
      const action = actions[names[0]];
      action.reset().fadeIn(0.5).play();
    }
  }, [actions, names]);

  const clonedScene = useMemo(() => {
    const clone = scene.clone()
    
    if (customColor) {
      clone.traverse((child) => {
        if (child.isMesh) {
          child.material = child.material.clone()
          child.material.color = new THREE.Color(customColor)
          if (child.material.emissive) {
             child.material.emissive = new THREE.Color(customColor)
          }
        }
      })
    }
    return clone
  }, [scene, customColor])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={3.293}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="WavyRingRoot_210">
                <group name="Ring_0_64" scale={0.987}>
                  <group name="Ring_0_Seg_0_0" position={[0.5, 0, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_1_1" position={[0.498, 0, 0.049]} rotation={[0, -0.098, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_2_2" position={[0.49, 0, 0.098]} rotation={[0, -0.196, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_3_3" position={[0.478, 0, 0.145]} rotation={[0, -0.295, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_4_4" position={[0.462, 0, 0.191]} rotation={[0, -Math.PI / 8, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_5_5" position={[0.441, 0, 0.236]} rotation={[0, -0.491, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_6_6" position={[0.416, 0, 0.278]} rotation={[0, -0.589, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_7_7" position={[0.387, 0, 0.317]} rotation={[0, -0.687, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_8_8" position={[0.354, 0, 0.354]} rotation={[0, -Math.PI / 4, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_9_9" position={[0.317, 0, 0.387]} rotation={[0, -0.884, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_10_10" position={[0.278, 0, 0.416]} rotation={[0, -0.982, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_11_11" position={[0.236, 0, 0.441]} rotation={[0, -1.08, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_12_12" position={[0.191, 0, 0.462]} rotation={[0, -1.178, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_13_13" position={[0.145, 0, 0.478]} rotation={[0, -1.276, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_14_14" position={[0.098, 0, 0.49]} rotation={[0, -1.374, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_15_15" position={[0.049, 0, 0.498]} rotation={[0, -1.473, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_16_16" position={[0, 0, 0.5]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_17_17" position={[-0.049, 0, 0.498]} rotation={[Math.PI, -1.473, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_18_18" position={[-0.098, 0, 0.49]} rotation={[Math.PI, -1.374, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_19_19" position={[-0.145, 0, 0.478]} rotation={[Math.PI, -1.276, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_20_20" position={[-0.191, 0, 0.462]} rotation={[Math.PI, -1.178, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_21_21" position={[-0.236, 0, 0.441]} rotation={[Math.PI, -1.08, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_22_22" position={[-0.278, 0, 0.416]} rotation={[Math.PI, -0.982, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_23_23" position={[-0.317, 0, 0.387]} rotation={[Math.PI, -0.884, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_24_24" position={[-0.354, 0, 0.354]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_25_25" position={[-0.387, 0, 0.317]} rotation={[Math.PI, -0.687, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_26_26" position={[-0.416, 0, 0.278]} rotation={[Math.PI, -0.589, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_27_27" position={[-0.441, 0, 0.236]} rotation={[Math.PI, -0.491, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_28_28" position={[-0.462, 0, 0.191]} rotation={[Math.PI, -Math.PI / 8, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_29_29" position={[-0.478, 0, 0.145]} rotation={[Math.PI, -0.295, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_30_30" position={[-0.49, 0, 0.098]} rotation={[Math.PI, -0.196, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_31_31" position={[-0.498, 0, 0.049]} rotation={[Math.PI, -0.098, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_32_32" position={[-0.5, 0, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_33_33" position={[-0.498, 0, -0.049]} rotation={[-Math.PI, 0.098, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_34_34" position={[-0.49, 0, -0.098]} rotation={[-Math.PI, 0.196, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_35_35" position={[-0.478, 0, -0.145]} rotation={[-Math.PI, 0.295, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_36_36" position={[-0.462, 0, -0.191]} rotation={[-Math.PI, Math.PI / 8, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_37_37" position={[-0.441, 0, -0.236]} rotation={[-Math.PI, 0.491, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_38_38" position={[-0.416, 0, -0.278]} rotation={[-Math.PI, 0.589, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_39_39" position={[-0.387, 0, -0.317]} rotation={[-Math.PI, 0.687, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_40_40" position={[-0.354, 0, -0.354]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_41_41" position={[-0.317, 0, -0.387]} rotation={[-Math.PI, 0.884, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_42_42" position={[-0.278, 0, -0.416]} rotation={[-Math.PI, 0.982, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_43_43" position={[-0.236, 0, -0.441]} rotation={[-Math.PI, 1.08, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_44_44" position={[-0.191, 0, -0.462]} rotation={[-Math.PI, 1.178, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_45_45" position={[-0.145, 0, -0.478]} rotation={[-Math.PI, 1.276, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_46_46" position={[-0.098, 0, -0.49]} rotation={[-Math.PI, 1.374, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_47_47" position={[-0.049, 0, -0.498]} rotation={[-Math.PI, 1.473, -Math.PI]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_48_48" position={[0, 0, -0.5]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_49_49" position={[0.049, 0, -0.498]} rotation={[0, 1.473, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_50_50" position={[0.098, 0, -0.49]} rotation={[0, 1.374, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_51_51" position={[0.145, 0, -0.478]} rotation={[0, 1.276, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_52_52" position={[0.191, 0, -0.462]} rotation={[0, 1.178, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_53_53" position={[0.236, 0, -0.441]} rotation={[0, 1.08, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_54_54" position={[0.278, 0, -0.416]} rotation={[0, 0.982, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_55_55" position={[0.317, 0, -0.387]} rotation={[0, 0.884, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_56_56" position={[0.354, 0, -0.354]} rotation={[0, Math.PI / 4, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_57_57" position={[0.387, 0, -0.317]} rotation={[0, 0.687, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_58_58" position={[0.416, 0, -0.278]} rotation={[0, 0.589, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_59_59" position={[0.441, 0, -0.236]} rotation={[0, 0.491, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_60_60" position={[0.462, 0, -0.191]} rotation={[0, Math.PI / 8, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_61_61" position={[0.478, 0, -0.145]} rotation={[0, 0.295, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_62_62" position={[0.49, 0, -0.098]} rotation={[0, 0.196, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_0_Seg_63_63" position={[0.498, 0, -0.049]} rotation={[0, 0.098, 0]} scale={[1, 0.013, 0.013]}>
                    <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material_0} />
                  </group>
                </group>
                <group name="Ring_1_129" scale={0.317}>
                  <group name="Ring_1_Seg_0_65" position={[0.5, 0, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_1_66" position={[0.498, 0, 0.049]} rotation={[0, -0.098, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_2_67" position={[0.49, 0, 0.098]} rotation={[0, -0.196, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_3_68" position={[0.478, 0, 0.145]} rotation={[0, -0.295, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_4_69" position={[0.462, 0, 0.191]} rotation={[0, -Math.PI / 8, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_5_70" position={[0.441, 0, 0.236]} rotation={[0, -0.491, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_6_71" position={[0.416, 0, 0.278]} rotation={[0, -0.589, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_7_72" position={[0.387, 0, 0.317]} rotation={[0, -0.687, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_8_73" position={[0.354, 0, 0.354]} rotation={[0, -Math.PI / 4, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_9_74" position={[0.317, 0, 0.387]} rotation={[0, -0.884, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_10_75" position={[0.278, 0, 0.416]} rotation={[0, -0.982, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_11_76" position={[0.236, 0, 0.441]} rotation={[0, -1.08, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_12_77" position={[0.191, 0, 0.462]} rotation={[0, -1.178, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_13_78" position={[0.145, 0, 0.478]} rotation={[0, -1.276, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_14_79" position={[0.098, 0, 0.49]} rotation={[0, -1.374, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_15_80" position={[0.049, 0, 0.498]} rotation={[0, -1.473, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_16_81" position={[0, 0, 0.5]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_17_82" position={[-0.049, 0, 0.498]} rotation={[Math.PI, -1.473, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_169" geometry={nodes.Object_169.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_18_83" position={[-0.098, 0, 0.49]} rotation={[Math.PI, -1.374, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_19_84" position={[-0.145, 0, 0.478]} rotation={[Math.PI, -1.276, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_20_85" position={[-0.191, 0, 0.462]} rotation={[Math.PI, -1.178, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_21_86" position={[-0.236, 0, 0.441]} rotation={[Math.PI, -1.08, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_22_87" position={[-0.278, 0, 0.416]} rotation={[Math.PI, -0.982, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_23_88" position={[-0.317, 0, 0.387]} rotation={[Math.PI, -0.884, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_24_89" position={[-0.354, 0, 0.354]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_25_90" position={[-0.387, 0, 0.317]} rotation={[Math.PI, -0.687, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_26_91" position={[-0.416, 0, 0.278]} rotation={[Math.PI, -0.589, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_27_92" position={[-0.441, 0, 0.236]} rotation={[Math.PI, -0.491, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_28_93" position={[-0.462, 0, 0.191]} rotation={[Math.PI, -Math.PI / 8, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_191" geometry={nodes.Object_191.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_29_94" position={[-0.478, 0, 0.145]} rotation={[Math.PI, -0.295, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_193" geometry={nodes.Object_193.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_30_95" position={[-0.49, 0, 0.098]} rotation={[Math.PI, -0.196, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_195" geometry={nodes.Object_195.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_31_96" position={[-0.498, 0, 0.049]} rotation={[Math.PI, -0.098, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_197" geometry={nodes.Object_197.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_32_97" position={[-0.5, 0, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_199" geometry={nodes.Object_199.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_33_98" position={[-0.498, 0, -0.049]} rotation={[-Math.PI, 0.098, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_34_99" position={[-0.49, 0, -0.098]} rotation={[-Math.PI, 0.196, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_203" geometry={nodes.Object_203.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_35_100" position={[-0.478, 0, -0.145]} rotation={[-Math.PI, 0.295, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_205" geometry={nodes.Object_205.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_36_101" position={[-0.462, 0, -0.191]} rotation={[-Math.PI, Math.PI / 8, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_37_102" position={[-0.441, 0, -0.236]} rotation={[-Math.PI, 0.491, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_38_103" position={[-0.416, 0, -0.278]} rotation={[-Math.PI, 0.589, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_211" geometry={nodes.Object_211.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_39_104" position={[-0.387, 0, -0.317]} rotation={[-Math.PI, 0.687, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_40_105" position={[-0.354, 0, -0.354]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_41_106" position={[-0.317, 0, -0.387]} rotation={[-Math.PI, 0.884, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_217" geometry={nodes.Object_217.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_42_107" position={[-0.278, 0, -0.416]} rotation={[-Math.PI, 0.982, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_43_108" position={[-0.236, 0, -0.441]} rotation={[-Math.PI, 1.08, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_44_109" position={[-0.191, 0, -0.462]} rotation={[-Math.PI, 1.178, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_223" geometry={nodes.Object_223.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_45_110" position={[-0.145, 0, -0.478]} rotation={[-Math.PI, 1.276, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_46_111" position={[-0.098, 0, -0.49]} rotation={[-Math.PI, 1.374, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_47_112" position={[-0.049, 0, -0.498]} rotation={[-Math.PI, 1.473, -Math.PI]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_48_113" position={[0, 0, -0.5]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_49_114" position={[0.049, 0, -0.498]} rotation={[0, 1.473, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_50_115" position={[0.098, 0, -0.49]} rotation={[0, 1.374, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_235" geometry={nodes.Object_235.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_51_116" position={[0.145, 0, -0.478]} rotation={[0, 1.276, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_52_117" position={[0.191, 0, -0.462]} rotation={[0, 1.178, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_239" geometry={nodes.Object_239.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_53_118" position={[0.236, 0, -0.441]} rotation={[0, 1.08, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_241" geometry={nodes.Object_241.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_54_119" position={[0.278, 0, -0.416]} rotation={[0, 0.982, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_243" geometry={nodes.Object_243.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_55_120" position={[0.317, 0, -0.387]} rotation={[0, 0.884, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_245" geometry={nodes.Object_245.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_56_121" position={[0.354, 0, -0.354]} rotation={[0, Math.PI / 4, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_247" geometry={nodes.Object_247.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_57_122" position={[0.387, 0, -0.317]} rotation={[0, 0.687, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_249" geometry={nodes.Object_249.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_58_123" position={[0.416, 0, -0.278]} rotation={[0, 0.589, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_251" geometry={nodes.Object_251.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_59_124" position={[0.441, 0, -0.236]} rotation={[0, 0.491, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_253" geometry={nodes.Object_253.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_60_125" position={[0.462, 0, -0.191]} rotation={[0, Math.PI / 8, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_255" geometry={nodes.Object_255.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_61_126" position={[0.478, 0, -0.145]} rotation={[0, 0.295, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_62_127" position={[0.49, 0, -0.098]} rotation={[0, 0.196, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_259" geometry={nodes.Object_259.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_1_Seg_63_128" position={[0.498, 0, -0.049]} rotation={[0, 0.098, 0]} scale={[1, 0.683, 0.683]}>
                    <mesh name="Object_261" geometry={nodes.Object_261.geometry} material={materials.material_0} />
                  </group>
                </group>
                <group name="Ring_2_194" scale={0.647}>
                  <group name="Ring_2_Seg_0_130" position={[0.5, 0, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_1_131" position={[0.498, 0, 0.049]} rotation={[0, -0.098, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_2_132" position={[0.49, 0, 0.098]} rotation={[0, -0.196, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_3_133" position={[0.478, 0, 0.145]} rotation={[0, -0.295, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_4_134" position={[0.462, 0, 0.191]} rotation={[0, -Math.PI / 8, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_5_135" position={[0.441, 0, 0.236]} rotation={[0, -0.491, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_6_136" position={[0.416, 0, 0.278]} rotation={[0, -0.589, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_7_137" position={[0.387, 0, 0.317]} rotation={[0, -0.687, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_8_138" position={[0.354, 0, 0.354]} rotation={[0, -Math.PI / 4, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_9_139" position={[0.317, 0, 0.387]} rotation={[0, -0.884, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_10_140" position={[0.278, 0, 0.416]} rotation={[0, -0.982, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_11_141" position={[0.236, 0, 0.441]} rotation={[0, -1.08, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_12_142" position={[0.191, 0, 0.462]} rotation={[0, -1.178, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_13_143" position={[0.145, 0, 0.478]} rotation={[0, -1.276, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_14_144" position={[0.098, 0, 0.49]} rotation={[0, -1.374, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_15_145" position={[0.049, 0, 0.498]} rotation={[0, -1.473, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_16_146" position={[0, 0, 0.5]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_17_147" position={[-0.049, 0, 0.498]} rotation={[Math.PI, -1.473, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_18_148" position={[-0.098, 0, 0.49]} rotation={[Math.PI, -1.374, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_19_149" position={[-0.145, 0, 0.478]} rotation={[Math.PI, -1.276, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_20_150" position={[-0.191, 0, 0.462]} rotation={[Math.PI, -1.178, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_21_151" position={[-0.236, 0, 0.441]} rotation={[Math.PI, -1.08, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_22_152" position={[-0.278, 0, 0.416]} rotation={[Math.PI, -0.982, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_23_153" position={[-0.317, 0, 0.387]} rotation={[Math.PI, -0.884, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_24_154" position={[-0.354, 0, 0.354]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_25_155" position={[-0.387, 0, 0.317]} rotation={[Math.PI, -0.687, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_26_156" position={[-0.416, 0, 0.278]} rotation={[Math.PI, -0.589, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_27_157" position={[-0.441, 0, 0.236]} rotation={[Math.PI, -0.491, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_28_158" position={[-0.462, 0, 0.191]} rotation={[Math.PI, -Math.PI / 8, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_29_159" position={[-0.478, 0, 0.145]} rotation={[Math.PI, -0.295, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_30_160" position={[-0.49, 0, 0.098]} rotation={[Math.PI, -0.196, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_31_161" position={[-0.498, 0, 0.049]} rotation={[Math.PI, -0.098, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_32_162" position={[-0.5, 0, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_33_163" position={[-0.498, 0, -0.049]} rotation={[-Math.PI, 0.098, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_34_164" position={[-0.49, 0, -0.098]} rotation={[-Math.PI, 0.196, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_35_165" position={[-0.478, 0, -0.145]} rotation={[-Math.PI, 0.295, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_36_166" position={[-0.462, 0, -0.191]} rotation={[-Math.PI, Math.PI / 8, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_37_167" position={[-0.441, 0, -0.236]} rotation={[-Math.PI, 0.491, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_38_168" position={[-0.416, 0, -0.278]} rotation={[-Math.PI, 0.589, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_39_169" position={[-0.387, 0, -0.317]} rotation={[-Math.PI, 0.687, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_40_170" position={[-0.354, 0, -0.354]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_41_171" position={[-0.317, 0, -0.387]} rotation={[-Math.PI, 0.884, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_42_172" position={[-0.278, 0, -0.416]} rotation={[-Math.PI, 0.982, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_43_173" position={[-0.236, 0, -0.441]} rotation={[-Math.PI, 1.08, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_44_174" position={[-0.191, 0, -0.462]} rotation={[-Math.PI, 1.178, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_45_175" position={[-0.145, 0, -0.478]} rotation={[-Math.PI, 1.276, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_46_176" position={[-0.098, 0, -0.49]} rotation={[-Math.PI, 1.374, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_47_177" position={[-0.049, 0, -0.498]} rotation={[-Math.PI, 1.473, -Math.PI]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_48_178" position={[0, 0, -0.5]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_49_179" position={[0.049, 0, -0.498]} rotation={[0, 1.473, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_50_180" position={[0.098, 0, -0.49]} rotation={[0, 1.374, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_51_181" position={[0.145, 0, -0.478]} rotation={[0, 1.276, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_52_182" position={[0.191, 0, -0.462]} rotation={[0, 1.178, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_53_183" position={[0.236, 0, -0.441]} rotation={[0, 1.08, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_54_184" position={[0.278, 0, -0.416]} rotation={[0, 0.982, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_55_185" position={[0.317, 0, -0.387]} rotation={[0, 0.884, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_56_186" position={[0.354, 0, -0.354]} rotation={[0, Math.PI / 4, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_57_187" position={[0.387, 0, -0.317]} rotation={[0, 0.687, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_58_188" position={[0.416, 0, -0.278]} rotation={[0, 0.589, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_59_189" position={[0.441, 0, -0.236]} rotation={[0, 0.491, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_60_190" position={[0.462, 0, -0.191]} rotation={[0, Math.PI / 8, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_61_191" position={[0.478, 0, -0.145]} rotation={[0, 0.295, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_62_192" position={[0.49, 0, -0.098]} rotation={[0, 0.196, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials.material_0} />
                  </group>
                  <group name="Ring_2_Seg_63_193" position={[0.498, 0, -0.049]} rotation={[0, 0.098, 0]} scale={[1, 0.353, 0.353]}>
                    <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials.material_0} />
                  </group>
                </group>
                <group name="Particle_0_195" position={[-0.188, 0.243, 0]} scale={0.675}>
                  <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_1_196" position={[0.053, 0.547, 0.024]} scale={0.271}>
                  <mesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_2_197" position={[-0.052, 0.597, -0.058]} scale={0.204}>
                  <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_3_198" position={[-0.062, 0.393, -0.191]} scale={0.475}>
                  <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_4_199" position={[0.014, 0.697, -0.135]} scale={0.071}>
                  <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_5_200" position={[0.146, 0.747, -0.253]} scale={0.004}>
                  <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_6_201" position={[-0.039, 0.543, 0.029]} scale={0.275}>
                  <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_7_202" position={[0.051, 0.097, -0.011]} scale={0.871}>
                  <mesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_8_203" position={[0.267, 0.147, 0.057]} scale={0.804}>
                  <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_9_204" position={[-0.177, 0.693, -0.129]} scale={0.075}>
                  <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_10_205" position={[0.005, 0.247, 0.009]} scale={0.671}>
                  <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_11_206" position={[-0.02, 0.297, -0.195]} scale={0.604}>
                  <mesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_12_207" position={[-0.091, 0.093, 0.281]} scale={0.875}>
                  <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_13_208" position={[0.181, 0.397, -0.201]} scale={0.471}>
                  <mesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials.material_0} />
                </group>
                <group name="Particle_14_209" position={[0.214, 0.447, -0.095]} scale={0.404}>
                  <mesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials.material_0} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      {clonedScene && <primitive object={clonedScene} />}
    </group>
  )
}

useGLTF.preload('/cyber_pulse.glb')
