/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cyberdeck_computer.glb --transform 
Files: public/cyberdeck_computer.glb [6.18MB] > C:\Users\jawha\OneDrive\Documents\code\portfo\cyberdeck_computer-transformed.glb [440.43KB] (93%)
Author: Michael V (https://sketchfab.com/bossdeff)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cyberdeck-computer-rpi-dev-f462376de53e4bfe84a95bc31a004972
Title: Cyberdeck Computer (RPI DEV)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function CyberdeckComputer(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/cyberdeck_computer-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Computer_Sec7_Back" position={[37.584, 0.82, -9.401]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="Monitor_1" position={[-0.19, 0.012, 0.15]}>
              <mesh name="Monitor_1_Sector7_RasPie_0" geometry={nodes.Monitor_1_Sector7_RasPie_0.geometry} material={materials.Sector7_RasPie} />
            </group>
            <group name="Monitor_2" position={[-0.19, 0.012, 0.15]}>
              <mesh name="Monitor_2_Sector7_RasPie_0" geometry={nodes.Monitor_2_Sector7_RasPie_0.geometry} material={materials.Sector7_RasPie} />
            </group>
            <mesh name="Computer_Sec7_Back_Sector7_RasPie_0" geometry={nodes.Computer_Sec7_Back_Sector7_RasPie_0.geometry} material={materials.Sector7_RasPie} />
          </group>
        </group>
        <mesh name="Computer_Sec7_Sector7_RasPie_0" geometry={nodes.Computer_Sec7_Sector7_RasPie_0.geometry} material={materials.Sector7_RasPie} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cyberdeck_computer-transformed.glb')
