/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/free_human_skull.glb --transform 
Files: public/free_human_skull.glb [1.42MB] > /home/nt-javkhlan_ts/Documents/code/portfo/free_human_skull-transformed.glb [119.54KB] (92%)
Author: riach (https://sketchfab.com/riach)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-human-skull-6a3c0f1b165a489db40c11912efe59c5
Title: Free Human Skull
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FreeHumanSkull(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL+'/free_human_skull-transformed.glb')
  materials['01_-_Default'].wireframe = true
  materials['01_-_Default'].color.set('#c9e3f3')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Quad_Sphere001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, -3.173, 4.513]} rotation={[-Math.PI / 2, 0, 0]} scale={37.736} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL+'/free_human_skull-transformed.glb')
