/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/houston_city_hall.glb --transform 
Files: public/houston_city_hall.glb [11.43MB] > /home/nt-javkhlan_ts/Documents/code/portfo/houston_city_hall-transformed.glb [138.96KB] (99%)
Author: Heitson_tron (https://sketchfab.com/Heitson_tron)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/houston-city-hall-f15e80edd72647ae91af2d723acb7694
Title: Houston City Hall
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HoustonCityHall(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL+'/houston_city_hall-transformed.glb')
  materials.lambert3.wireframe = true

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface7_lambert3_0.geometry} material={materials.lambert3} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/houston_city_hall-transformed.glb')
