/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/lamp_post.glb --transform 
Files: public/lamp_post.glb [117.17KB] > /home/nt-javkhlan_ts/Documents/code/portfo/lamp_post-transformed.glb [13.74KB] (88%)
Author: CrazyPolski103 (https://sketchfab.com/goofy_ah_pole)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/moscow-lamp-post-2cfd9d36706940ce96ff3bbbc98416ac
Title: Moscow Lamp Post
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LampPost(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL+'/lamp_post-transformed.glb')
  materials['Material.001'].wireframe = true
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.234} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL+'/lamp_post-transformed.glb')
