/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/sci-fi_computer.glb --transform 
Files: public/sci-fi_computer.glb [16.42MB] > C:\Users\jawha\OneDrive\Documents\code\portfo\sci-fi_computer-transformed.glb [1.8MB] (89%)
Author: Render Blue (https://sketchfab.com/pablojcd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-computer-43f296dbc51b40e2b80cb90698c2837b
Title: Sci-fi Computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sci-fi_computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Pantalla} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Detalles} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Bisagras} />
      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Bases} />
      <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Marcos} />
      <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Forros} />
      <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Carcasa_2} />
      <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Carcasa_1} />
    </group>
  )
}

useGLTF.preload('/sci-fi_computer-transformed.glb')
