/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/surveillance_room.glb --transform 
Files: public/surveillance_room.glb [29.24MB] > /home/nt-javkhlan_ts/Documents/code/portfo/surveillance_room-transformed.glb [1.21MB] (96%)
Author: wa_rouk (https://sketchfab.com/wa_rouk)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/surveillance-room-7fd56cd3917443a99966352beefd8304
Title: Surveillance room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function SurveillanceRoom(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL+'/surveillance_room-transformed.glb')
  materials.material.wireframe = true
  materials.Shading2_cables.wireframe = true
  materials.Shading1.wireframe = true
  materials.Lumires.wireframe = true

  materials.material.color = new THREE.Color(0xc9e3f3)
  materials.Shading2_cables.color = new THREE.Color(0xc9e3f3)
  materials.Shading1.color = new THREE.Color(0xc9e3f3)
  materials.Lumires.color = new THREE.Color(0xc9e3f3)

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[2.09, -0.853, 2.109]} scale={0.192} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Shading2_cables} position={[2.09, -0.853, 2.109]} scale={0.192} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Shading1} position={[2.09, -0.853, 2.109]} scale={0.192} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Lumires} position={[2.09, -0.853, 2.109]} scale={0.192} />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL+'/surveillance_room-transformed.glb')
