/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/wireframe_man.glb --transform 
Files: public/wireframe_man.glb [3.69MB] > C:\Users\jawha\OneDrive\Documents\code\portfo\wireframe_man-transformed.glb [417.05KB] (89%)
Author: Doomcubus (https://sketchfab.com/Doomcubus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wireframe-man-44764d68c52a43a7aa981761f508d10b
Title: Wireframe Man
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function WireframeMan(props) {
  const { scene } = useGLTF('/wireframe_man-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} skeleton={nodes.Object_7.skeleton} position={[0, 0, -0.137]} rotation={[-Math.PI / 2, 0, 0]} scale={4.302} />
    </group>
  )
}

useGLTF.preload('/wireframe_man-transformed.glb')
